# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
  ldflags: -X "github.com/joshuabeny1999/telegram-server-update-bot/cmd.version={{.Version}}" -X "github.com/joshuabeny1999/telegram-server-update-bot/cmd.commit={{.Commit}}" -X "github.com/joshuabeny1999/telegram-server-update-bot/cmd.date={{.Date}}"
archives:
- replacements:
    linux: Linux
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
